# Generated by Django 4.1.7 on 2024-01-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
    ]
